### ISSUE TITLE
How do you manage the list size?

### ISSUE THREAD

**Issue by jhbirdchoi** [SidMurthy97/Plant_monitor#1]
Hi

I tested the ur project.
It works well. Great.

But I met a problem. 
This list size keeps growing, causing problems in long tests. (there was a problem of exceeding the stack size in the web.)
Do you have a good ideas?

thanks

temperature = []
humidity = []
soil_moisture = []
time_ax = []

@app.route("/update", methods = ['GET'])
def update_chart():

    while not q.empty():
        temperature.append(q.get())
        humidity.append(q.get())
        soil_moisture.append(q.get())
        time_ax.append(q.get())

    return jsonify(results = [temperature,humidity,soil_moisture,time_ax])

thanks

**Comment by SidMurthy97** [comment]
Hi,

I'm glad you're finding my project and write up useful. When I first
designed it, it was only meant to be run for a day or two and not for long
periods of time. That being said, there are ways you can modify the code to
your needs. If you're wanting to record data for many days (say a week) and
you want to be able to view the data, you'll have to write the data out of
dynamic memory e.g. to a database or an excel file. If you're not familiar
with databases, an excel file is quite easy to get setup using python, this
is the way I would do it. On the other hand, if you simply want to record
the data and are not so bothered about seeing data from the previous days,
you can use something called a deque from the collections library in
python. This would mean making temperature, humidity,soil_moisture, and
time_ax a deque instead of a list. A deque is essentially a double-sided
queue, you set a size and it removes data from the front of it when the
size is exceeded. In this case, you can set the size of the deque to be the
number of samples the system takes in a week, then any data older than a
week gets removed from the chart. These are the two things I can think of
from the top of my head. The code I've written is not very efficient for
long periods of time so if you're planning on running it for a while then
definitely consider one of the options I have outlined here. Also, feel
free to fork the git repo and make your own changes, I've always wanted to
improve the system but never had time!

Here are some useful links to documentation and code samples:
deque: https://docs.python.org/3/library/collections.html
excel:
https://www.geeksforgeeks.org/python-create-and-write-on-excel-file-using-xlsxwriter-module/

If you are familiar with python, try using Pandas dataframes to store the
data, this makes it much easier to convert data to excel.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html

I hope you have luck with modifying the project.

Best,
Sid

**Comment by jhbirdchoi** [comment]
Thanks for the kind answer.~~
